---
- name: Installing Zsh and git
  apt: pkg=zsh,git state=latest
  register: installation
  become: true

- name: Check if .zshrc exists
  stat:
    path: /root/.zshrc
  register: stat_rc_result
  become: true

- name: Check if .oh-my-zsh exists
  stat:
    path: /root/.oh-my-zsh
  register: stat_oh_my_zsh_result
  become: true

- name: Cloning  oh-my-zsh
  git:
    repo=https://github.com/robbyrussell/oh-my-zsh
    dest=/root/.oh-my-zsh
  when: not stat_oh_my_zsh_result.stat.exists
  become: true

- name: Stowing zsh and oh-my-zsh
  shell:
    chdir: /root/dotfiles
    cmd: stow zsh
  when: not stat_rc_result.stat.exists

- name: Stowing zsh and oh-my-zsh
  shell:
    chdir: /root/dotfiles
    cmd: stow oh-my-zsh
  when: not stat_rc_result.stat.exists

- name: Changing default shell
  shell:
    cmd: chsh -s /bin/zsh
