---
- name: Update sources
  become: true
  apt:
    update_cache: yes

- name: Installing neovim
  become: true
  apt:
    name: neovim

- name: Installing neovim
  become: true
  apt:
    name: fzf
